logging_formats:
  string_format: "%(asctime)s: %(levelname)s: %(message)s"
  "date_format": "%d-%m-%Y %H:%M:%S"
date_time_formats:
    "dmy_slashes": "%d/%m/%Y"
    "dmy": "%d%m%y"
log_file_name: "debug.log"
initial_folder_structure:
   - "Images"
   - "Videos"
   - "Audio"
