logging_formats:
  string_format: "%(asctime)s: %(levelname)s: %(message)s"
  "date_format": "%d-%m-%Y %H:%M:%S"
date_time_formats:
    "dmy_slashes": "%d/%m/%Y"
    "dmy": "%d%m%y"
log_file_name: "debug.log"
initial_folder_structure:
   - "Images"
   - "Videos"
   - "Audio"
image_file_extensions:
  - ".jpg"
  - ".png"
  - ".gif"
  - ".jpeg"
  - ".heic"
video_file_extensions:
  - ".mp4"
  - ".mov"
  - ".avi"
audio_file_extensions:
  - ".mp3"
  - ".wav"
